<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>07ae77b7-a8e5-4619-a7ec-521d188a7925</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="DTOs\Users\LoginRequest.DTO.cs" />
    <None Include="DTOs\Users\RegisterUserRequest.DTO.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManager.Domain\EventManager.Domain.csproj" />
  </ItemGroup>

</Project>
