<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5ae0d437-655a-4132-a7b1-48cbef56757e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManager.Application\EventManager.Application.csproj" />
    <ProjectReference Include="..\EventManager.Infrastructure\EventManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
